/**
 * SEO Constants
 * Default SEO configuration and category-specific keywords for NovAura
 */

export const DEFAULT_SEO = {
  siteName: 'NovAura',
  siteUrl: 'https://novauraverse.com',
  defaultTitle: 'NovAura - The Creator Ecosystem',
  defaultDescription: 'The ethical creator marketplace. Buy, sell, and create game assets, 3D models, software, and digital experiences. Empowering creators with fair royalties and a supportive community.',
  defaultImage: '/og-image.jpg',
  twitterHandle: '@novaura',
  facebookAppId: '',
  locale: 'en_US',
  themeColor: '#6d28d9',
} as const;

export const CATEGORY_KEYWORDS: Record<string, string[]> = {
  'game-assets': [
    'game assets',
    'game development',
    'indie game assets',
    'game sprites',
    'game textures',
    'game audio',
    'game music',
    'sound effects',
    'game UI',
    'game icons',
  ],
  '3d-models': [
    '3D models',
    '3D assets',
    'Blender models',
    'Maya models',
    'character models',
    'environment models',
    'prop models',
    'low poly models',
    'PBR textures',
    '3D printing models',
  ],
  '2d-art': [
    '2D art',
    'pixel art',
    'vector art',
    'concept art',
    'illustrations',
    'game sprites',
    'tilesets',
    'UI elements',
    'character art',
    'background art',
  ],
  'animations': [
    'animations',
    '3D animations',
    '2D animations',
    'motion graphics',
    'character animations',
    'VFX',
    'visual effects',
    'animation loops',
    'animated sprites',
  ],
  'audio': [
    'game audio',
    'sound effects',
    'SFX',
    'background music',
    'BGM',
    'audio loops',
    'voice acting',
    'ambient sounds',
    'music packs',
    'audio assets',
  ],
  'tools': [
    'game development tools',
    'Unity plugins',
    'Unreal Engine plugins',
    'Godot addons',
    'development tools',
    'code libraries',
    'scripts',
    'shaders',
    'editor extensions',
  ],
  'templates': [
    'game templates',
    'project templates',
    'starter kits',
    'game kits',
    'RPG templates',
    'platformer templates',
    'FPS templates',
    'game frameworks',
  ],
  'vr-ar': [
    'VR assets',
    'AR assets',
    'virtual reality',
    'augmented reality',
    'XR assets',
    'Meta Quest',
    'Oculus',
    'ARKit',
    'ARCore',
    'immersive experiences',
  ],
  'software': [
    'developer tools',
    'software utilities',
    'automation tools',
    'analytics tools',
    'deployment tools',
    'dev aids',
    'productivity software',
  ],
  'games': [
    'indie games',
    'game projects',
    'full games',
    'game source code',
    'complete games',
    'game prototypes',
    'game demos',
    ' playable games',
  ],
} as const;

export const ENGINE_KEYWORDS: Record<string, string[]> = {
  'unity': ['Unity assets', 'Unity 3D', 'Unity games', 'Unity development', 'Unity store'],
  'unreal': ['Unreal Engine', 'UE4', 'UE5', 'Unreal assets', 'Unreal Marketplace'],
  'godot': ['Godot engine', 'Godot assets', 'Godot addons', 'open source game engine'],
  'web': ['WebGL', 'HTML5 games', 'JavaScript games', 'browser games', 'web development'],
  'other': ['game engine agnostic', 'universal assets', 'cross-platform'],
} as const;

export const COMPLEXITY_KEYWORDS: Record<string, string[]> = {
  'beginner': ['beginner friendly', 'easy to use', 'starter assets', 'novice'],
  'intermediate': ['intermediate', 'moderate complexity', 'mid-level'],
  'advanced': ['advanced', 'professional', 'expert level', 'complex'],
} as const;

export const STATIC_ROUTES = [
  { path: '/', priority: 1.0, changefreq: 'daily' as const },
  { path: '/browse', priority: 0.9, changefreq: 'daily' as const },
  { path: '/domains', priority: 0.8, changefreq: 'weekly' as const },
  { path: '/hosting', priority: 0.8, changefreq: 'weekly' as const },
  { path: '/about', priority: 0.8, changefreq: 'monthly' as const },
  { path: '/investors', priority: 0.7, changefreq: 'monthly' as const },
  { path: '/email', priority: 0.7, changefreq: 'monthly' as const },
  { path: '/help', priority: 0.6, changefreq: 'monthly' as const },
  { path: '/contact', priority: 0.6, changefreq: 'monthly' as const },
  { path: '/blog', priority: 0.8, changefreq: 'weekly' as const },
  { path: '/community', priority: 0.8, changefreq: 'daily' as const },
  { path: '/gallery', priority: 0.7, changefreq: 'daily' as const },
  { path: '/creators', priority: 0.9, changefreq: 'daily' as const },
  { path: '/jobs', priority: 0.7, changefreq: 'daily' as const },
  { path: '/forum', priority: 0.8, changefreq: 'hourly' as const },
  { path: '/legal/terms', priority: 0.4, changefreq: 'yearly' as const },
  { path: '/legal/privacy', priority: 0.4, changefreq: 'yearly' as const },
  { path: '/legal/licensing', priority: 0.5, changefreq: 'monthly' as const },
  { path: '/login', priority: 0.3, changefreq: 'never' as const },
  { path: '/signup', priority: 0.3, changefreq: 'never' as const },
  { path: '/creator/dashboard', priority: 0.5, changefreq: 'always' as const },
  { path: '/cart', priority: 0.3, changefreq: 'never' as const },
  { path: '/wishlist', priority: 0.4, changefreq: 'always' as const },
  { path: '/creator/assets/new', priority: 0.5, changefreq: 'never' as const },
  { path: '/notifications', priority: 0.3, changefreq: 'always' as const },
  { path: '/messages', priority: 0.4, changefreq: 'always' as const },
  { path: '/creator/earnings', priority: 0.4, changefreq: 'always' as const },
  { path: '/settings', priority: 0.3, changefreq: 'never' as const },
] as const;

export const DYNAMIC_ROUTE_PATTERNS = [
  { pattern: '/asset/:slug', priority: 0.8, changefreq: 'weekly' as const },
  { pattern: '/creator/:username', priority: 0.7, changefreq: 'daily' as const },
  { pattern: '/category/:slug', priority: 0.8, changefreq: 'weekly' as const },
  { pattern: '/blog/:slug', priority: 0.6, changefreq: 'never' as const },
  { pattern: '/forum/thread/:id', priority: 0.6, changefreq: 'hourly' as const },
  { pattern: '/gallery/:id', priority: 0.5, changefreq: 'never' as const },
  { pattern: '/jobs/:id', priority: 0.6, changefreq: 'daily' as const },
  { pattern: '/order/:id', priority: 0.3, changefreq: 'never' as const },
  { pattern: '/user/:username', priority: 0.5, changefreq: 'daily' as const },
] as const;

export const META_LIMITS = {
  titleMaxLength: 60,
  descriptionMaxLength: 160,
  keywordsMaxCount: 10,
} as const;
